name: Warden Magazine
favicon: null
layout_spectrum: 0.76127
typography_spectrum: 0.85081
title: Warden Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbdbdb'
    - '#173857'
    - '#697c90'
    - '#9ba4ab'
    - '#bec7d1'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
