name: Warden Magazine
favicon: null
layout_spectrum: 0.50346
typography_spectrum: 0.85366
title: Warden Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbdbdb'
    - '#173857'
    - '#697c90'
    - '#9ba4ab'
    - '#bec7d1'
  brandStrength: 0.4263849512208253
  lightness: 0.3132620232645422
  saturation: 0.09375879191793501
  rhythmicContrast: 0.18110034754499793
purpose: []
